In [1]:
import numpy as np
import pandas as pd
import OpenEXR
import re
import sys
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image, ImageDraw

In [2]:
csvPath = Path(r"C:\Users\sol77\Desktop\ML-For-CV-Robustness\miscellaneous\grviValues.csv")
csvPath.is_file()

True

In [3]:
grvi_gt_raw = pd.read_csv(csvPath)
grvi_gt_raw

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12
0,0.20,0.20,0.22,0.32,0.30,0.30,0.10,0.24,0.32,0.36,0.34,0.34,0.36
1,0.22,0.30,0.34,0.34,0.28,0.18,0.30,0.36,0.38,0.36,0.36,0.34,0.36
2,0.26,0.24,0.26,0.26,0.32,0.32,0.36,0.36,0.36,0.38,0.36,0.34,0.36
3,0.28,0.32,0.36,0.26,0.34,0.34,0.36,0.36,0.38,0.38,0.34,0.26,0.36
4,0.32,0.34,0.34,0.36,0.36,0.26,0.32,0.38,0.38,0.36,0.36,0.32,0.38
5,0.34,0.34,0.36,0.28,0.36,0.20,0.30,0.36,0.38,0.36,0.32,0.30,0.36
6,0.34,0.32,0.10,0.34,0.34,0.16,0.26,0.36,0.36,0.36,0.26,0.28,0.34
7,0.30,0.30,0.16,0.36,0.34,0.32,0.26,0.34,0.32,0.34,0.30,0.32,0.38
8,0.34,0.26,0.36,0.36,0.34,0.14,0.22,0.34,0.34,0.30,0.32,0.28,0.36
9,0.08,0.30,0.36,0.36,0.32,0.12,0.30,0.30,0.32,0.32,0.26,0.28,0.36
10,0.20,0.34,0.34,0.36,0.34,0.14,0.24,0.32,0.30,0.30,0.32,0.30,0.36
11,0.26,0.30,0.32,0.30,0.34,0.14,0.26,0.34,0.30,0.26,0.26,0.22,0.36
12,0.26,0.28,0.22,0.30,0.30,0.10,0.36,0.34,0.34,0.36,0.34,0.28,0.34
13,0.20,0.32,0.24,0.26,0.30,0.18,0.16,0.32,0.28,0.30,0.26,0.26,0.34

In [4]:
cameraPathPath = Path(r"C:\Users\sol77\Desktop\ML-For-CV-Robustness\miscellaneous\ObjectPoses_back.txt")

In [5]:
with open(str(cameraPathPath), "r") as f:
     cameraPathFile = f.readlines()

In [6]:
cameraCoords = []
cameraRot = []

for line in cameraPathFile:
    xyz = []
    
    numbers = re.findall(r'-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?', line)

    xyz.append(float(numbers[1]))
    xyz.append(float(numbers[2]))

    cameraCoords.append(xyz)
    cameraRot.append(float(numbers[6]))

In [7]:
jsks = []

for i in range (0, len(cameraCoords)):
    coords = cameraCoords[i]

    if cameraRot[i] == 0:
        j = 0
        while True:
            if coords[0]+400 < ((-14840) + j*1900):
                break
                
            j = j + 1
        j = j - 1
        
        for l in range (0, 20):
            k = 0
            while True:
                if coords[1] - 340 + (l+0.5)*(680/20) < ((-14780) + k*1900):
                    break
    
                k = k + 1
            k = k - 1
            if (k == 13):
                k = 12

            jsks.append([j, k])
    
    elif cameraRot[i] == -180:
        j = 0
        while True:
            if coords[0]-400 < ((-14840) + j*1900):
                break
                
            j = j + 1
        j = j - 1
        
        for l in range (0, 20):
            k = 0
            while True:
                if coords[1] + 340 - (l+0.5)*(680/20) < ((-14780) + k*1900):
                    break
    
                k = k + 1
            k = k - 1
            if (k == 13):
                k = 12

            jsks.append([j, k]) 
    else:
        j = 0
        while True:
            if coords[0] < ((-14840) + j*1900):
                break
                
            j = j + 1
        j = j - 1

        for l in range (0, 20):
            k = 0
            while True:
                if coords[1] + 400 < ((-14780) + k*1900):
                    break
    
                k = k + 1
            k = k - 1
            if (k == 13):
                k = 12

            jsks.append([j, k])
        
jsks

[[0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [0, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [1, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [2, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [3, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [4, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [5, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [6, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [7, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [8, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [9, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [10, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [11, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [12, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 12],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [13, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [12, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [11, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [10, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [9, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [8, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [7, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [6, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [5, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [4, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [3, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [2, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [1, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 [0, 11],
 ...]

In [8]:
len(jsks)

5960

In [9]:
grviOut = []

for i in range (0, len(jsks)):
    jk = jsks[i]
    if (jk[1] == 13):
        print (i)
        break
    
    grviOut.append(grvi_gt_raw.iloc[13-jk[0], jk[1]])

In [10]:
len(grviOut)

5960

In [11]:
data = pd.DataFrame({"grviOut": grviOut})

In [12]:
data

      grviOut
0        0.34
1        0.34
2        0.34
3        0.34
4        0.34
...       ...
5955     0.26
5956     0.26
5957     0.26
5958     0.26
5959     0.26

[5960 rows x 1 columns]

In [13]:
data.to_csv(r"D:\ThesisData\groundtruthGRVI-back.csv", index=False)