In [1]:
!pip install autogluon.tabular

Collecting autogluon.tabular
  Downloading autogluon_tabular-1.6.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy<2.6.0,>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (2.1.3)
Requirement already satisfied: scipy<1.19,>=1.5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (2.2.3)
Requirement already satisfied: scikit-learn<1.10.0,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (3.6.1)
Collecting autogluon.core==1.6.1 (from autogluon.tabular)
  Downloading autogluon_core-1.6.1-py3-none-any.whl.metadata (14 kB)
Collecting autogluon.features==1.6.1 (from autogluon.tabular)
  Downloading autogluon_features-1.6.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.1->autogluon.tabular) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.1->autogluon.tabular) (2.32.4)
Requirement already satisfied: matplotlib<3.12,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.1->autogluon.tabular) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.6.1->autogluon.tabular)
  Downloading boto3-1.43.78-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions<5,>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.1->autogluon.tabular) (4.16.0)
Collecting autogluon.common==1.6.1 (from autogluon.core==1.6.1->autogluon.tabular)
  Downloading autogluon_common-1.6.1-py3-none-any.whl.metadata (13 kB)
Collecting pyarrow<25.0.0,>=23.0.1 (from autogluon.common==1.6.1->autogluon.core==1.6.1->autogluon.tabular)
  Downloading pyarrow-24.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: psutil<7.3.0,>=5.7.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.1->autogluon.core==1.6.1->autogluon.tabular) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.1->autogluon.core==1.6.1->autogluon.tabular) (1.5.3)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.1->autogluon.core==1.6.1->autogluon.tabular) (6.0.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.1->autogluon.core==1.6.1->autogluon.tabular) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2026.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.10.0,>=1.4.0->autogluon.tabular) (3.6.0)
Collecting botocore<1.44.0,>=1.43.78 (from boto3<2,>=1.10->autogluon.core==1.6.1->autogluon.tabular)
  Downloading botocore-1.43.78-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.6.1->autogluon.tabular)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2,>=1.10->autogluon.core==1.6.1->autogluon.tabular)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.1->autogluon.tabular) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->autogluon.tabular) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.1->autogluon.tabular) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.1->autogluon.tabular) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.1->autogluon.tabular) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.1->autogluon.tabular) (2026.7.22)
Downloading autogluon_tabular-1.6.1-py3-none-any.whl (514 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 514.8/514.8 kB 18.0 MB/s eta 0:00:00
Downloading autogluon_core-1.6.1-py3-none-any.whl (248 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.4/248.4 kB 25.3 MB/s eta 0:00:00
Downloading autogluon_features-1.6.1-py3-none-any.whl (112 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 kB 12.1 MB/s eta 0:00:00
Downloading autogluon_common-1.6.1-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.7/90.7 kB 10.2 MB/s eta 0:00:00
Downloading boto3-1.43.78-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 15.6 MB/s eta 0:00:00
Downloading botocore-1.43.78-py3-none-any.whl (15.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 79.2 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading pyarrow-24.0.0-cp313-cp313-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 16.5 MB/s eta 0:00:00
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 8.5 MB/s eta 0:00:00
Installing collected packages: pyarrow, jmespath, botocore, s3transfer, boto3, autogluon.common, autogluon.features, autogluon.core, autogluon.tabular
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
Successfully installed autogluon.common-1.6.1 autogluon.core-1.6.1 autogluon.features-1.6.1 autogluon.tabular-1.6.1 boto3-1.43.78 botocore-1.43.78 jmespath-1.1.0 pyarrow-24.0.0 s3transfer-0.19.2

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
import os
import pandas as pd
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

In [15]:
datasetPath = Path("/content/drive/MyDrive/ML-For-CV-Robustness/datasets/notrees.csv")

#making sure
datasetPath.is_file()

True

In [16]:
dataset = pd.read_csv(datasetPath)
dataset.head()

,grviIn,meanRefR,meanRefG,illumR,illumG,blockIdx,sunRoll,sunPitch,sunYaw,camRoll,camPitch,camYaw,grviOut
0,0.163549,0.000324,0.000421,1130.973355,1020.232214,0.0,180.0,-63.812729,-56.07412,0.0,-19.258,-0.0,0.088270
1,0.097110,0.000412,0.000486,1130.973355,1020.232214,1.0,180.0,-63.812729,-56.07412,0.0,-19.258,-0.0,0.057202
2,0.074345,0.000448,0.000517,1130.973355,1020.232214,2.0,180.0,-63.812729,-56.07412,0.0,-19.258,-0.0,0.048503
3,0.156574,0.000374,0.000481,1130.973355,1020.232214,3.0,180.0,-63.812729,-56.07412,0.0,-19.258,-0.0,0.086477
4,0.116627,0.000393,0.000479,1130.973355,1020.232214,4.0,180.0,-63.812729,-56.07412,0.0,-19.258,-0.0,0.067095

In [17]:
from autogluon.tabular import TabularPredictor

In [18]:
train_df = dataset.sample(frac=0.8, random_state=42)
test_df = dataset.drop(train_df.index)

In [19]:
train_df

,grviIn,meanRefR,meanRefG,illumR,illumG,blockIdx,sunRoll,sunPitch,sunYaw,camRoll,camPitch,camYaw,grviOut
142331,0.145998,0.000409,0.000513,531.714557,479.878278,11.0,180.0,-63.688171,56.363342,0.0,-19.532,-0.000,0.078595
270207,0.311861,0.000227,0.000388,368.744438,321.424198,7.0,180.0,-42.151062,85.965363,0.0,-19.320,-0.000,0.137009
49351,0.270059,0.000188,0.000296,220.893233,200.472881,11.0,180.0,-71.945084,19.489212,0.0,-22.271,180.000,0.093232
169549,0.229224,0.000165,0.000216,1130.973355,1020.232214,9.0,180.0,-63.812729,-56.074120,-0.0,-22.112,-180.000,0.086487
31301,0.304657,0.000192,0.000316,1334.391480,1020.232214,1.0,180.0,-19.763107,-104.398338,0.0,-22.510,180.000,0.129195
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304611,0.233003,0.000227,0.000312,531.714557,479.878278,11.0,180.0,-63.688171,56.363342,-0.0,-21.426,-180.000,0.080990
119616,0.270809,0.000170,0.000217,370.118885,322.798645,16.0,180.0,-42.301559,-85.835487,0.0,-19.813,81.537,0.088975
59809,0.250882,0.000259,0.000396,228.550866,199.294784,9.0,180.0,-42.151062,85.965363,0.0,-18.992,-0.000,0.101696
273354,0.222158,0.000413,0.000600,368.744438,321.424198,14.0,180.0,-42.151062,85.965363,-0.0,-18.932,-0.000,0.094931
178451,0.220230,0.000163,0.000210,1124.690170,1020.232214,11.0,180.0,-71.945084,19.489212,-0.0,-22.500,-180.000,0.078932

In [20]:
test_df

,grviIn,meanRefR,meanRefG,illumR,illumG,blockIdx,sunRoll,sunPitch,sunYaw,camRoll,camPitch,camYaw,grviOut
5,0.081775,0.000463,0.000538,1130.973355,1020.232214,5.0,180.0,-63.812729,-56.074120,0.0,-19.258,-0.0,0.053121
13,0.108716,0.000371,0.000444,1130.973355,1020.232214,13.0,180.0,-63.812729,-56.074120,0.0,-19.258,-0.0,0.066583
15,0.144419,0.000328,0.000411,1130.973355,1020.232214,15.0,180.0,-63.812729,-56.074120,0.0,-19.258,-0.0,0.087779
18,0.167532,0.000247,0.000317,1130.973355,1020.232214,18.0,180.0,-63.812729,-56.074120,0.0,-19.258,-0.0,0.094252
19,0.185488,0.000243,0.000321,1130.973355,1020.232214,19.0,180.0,-63.812729,-56.074120,0.0,-19.258,-0.0,0.097285
...,...,...,...,...,...,...,...,...,...,...,...,...,...
333458,0.296286,0.000274,0.000436,550.956812,480.270977,18.0,180.0,-42.301559,-85.835487,-0.0,-22.204,-180.0,0.105932
333460,0.267418,0.000102,0.000135,550.956812,480.270977,0.0,180.0,-42.301559,-85.835487,-0.0,-22.218,-180.0,0.101249
333470,0.239545,0.000260,0.000367,550.956812,480.270977,10.0,180.0,-42.301559,-85.835487,-0.0,-22.218,-180.0,0.084095
333473,0.259494,0.000291,0.000437,550.956812,480.270977,13.0,180.0,-42.301559,-85.835487,-0.0,-22.218,-180.0,0.085348
333475,0.262388,0.000241,0.000365,550.956812,480.270977,15.0,180.0,-42.301559,-85.835487,-0.0,-22.218,-180.0,0.087821

In [21]:
predictor = TabularPredictor(
    label="grviOut",
    problem_type="regression",
    eval_metric="root_mean_squared_error"
).fit(
    train_data=train_df
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260822_145624"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.1
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.11.0+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       10.71 GB / 12.67 GB (84.5%)
Disk Space Avail:   10.57 GB / 15.00 GB (70.5%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (266784 samples, 29.88 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/content/drive/MyDrive/ML-For-CV-Robustness/datasets/AutogluonModels/ag-20260822_145624"
Train Data Rows:    266784
Train Data Columns: 12
Label Column:       grviOut
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10917.47 MB
	Train Data (Original)  Memory Usage: 24.42 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 2): ['sunRoll', 'camRoll']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 10 | ['grviIn', 'meanRefR', 'meanRefG', 'illumR', 'illumG', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 10 | ['grviIn', 'meanRefR', 'meanRefG', 'illumR', 'illumG', ...]
	0.7s = Fit runtime
	10 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 20.35 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 0.76s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.01, Train Rows: 264116, Val Rows: 2668
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=1, gpus=0, mem=0.2/10.6 GB

[1000]	valid_set's rmse: 0.00685107
[2000]	valid_set's rmse: 0.00631546
[3000]	valid_set's rmse: 0.00605433
[4000]	valid_set's rmse: 0.00589367
[5000]	valid_set's rmse: 0.0057869
[6000]	valid_set's rmse: 0.0057035
[7000]	valid_set's rmse: 0.00563611
[8000]	valid_set's rmse: 0.00558198
[9000]	valid_set's rmse: 0.00553672
[10000]	valid_set's rmse: 0.00549514

	-0.0055	 = Validation score   (-root_mean_squared_error)
	160.08s	 = Training   runtime
	2.89s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=1, gpus=0, mem=0.2/10.5 GB

[1000]	valid_set's rmse: 0.00620989
[2000]	valid_set's rmse: 0.0057276
[3000]	valid_set's rmse: 0.00551158
[4000]	valid_set's rmse: 0.00535588
[5000]	valid_set's rmse: 0.0052566
[6000]	valid_set's rmse: 0.00518657
[7000]	valid_set's rmse: 0.00512055
[8000]	valid_set's rmse: 0.00506935
[9000]	valid_set's rmse: 0.005027
[10000]	valid_set's rmse: 0.00499056

	-0.005	 = Validation score   (-root_mean_squared_error)
	111.61s	 = Training   runtime
	1.96s	 = Validation runtime
Fitting model: RandomForestMSE ...
	Fitting with cpus=2, gpus=0, mem=1.3/10.5 GB
	-0.0066	 = Validation score   (-root_mean_squared_error)
	561.03s	 = Training   runtime
	0.31s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=1, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.6.1`.
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=2, gpus=0, mem=1.3/10.5 GB
	-0.006	 = Validation score   (-root_mean_squared_error)
	109.63s	 = Training   runtime
	0.28s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=1, gpus=0, mem=0.2/10.4 GB
	-0.0069	 = Validation score   (-root_mean_squared_error)
	191.17s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=1, gpus=0
	-0.0049	 = Validation score   (-root_mean_squared_error)
	103.94s	 = Training   runtime
	0.27s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=1, gpus=0, mem=0.1/10.0 GB
	-0.0057	 = Validation score   (-root_mean_squared_error)
	690.27s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=1, gpus=0, mem=0.2/10.0 GB

[1000]	valid_set's rmse: 0.00557712
[2000]	valid_set's rmse: 0.00525023
[3000]	valid_set's rmse: 0.00507904
[4000]	valid_set's rmse: 0.00495934
[5000]	valid_set's rmse: 0.00487338
[6000]	valid_set's rmse: 0.00481768
[7000]	valid_set's rmse: 0.00476958
[8000]	valid_set's rmse: 0.00473911
[9000]	valid_set's rmse: 0.00471085
[10000]	valid_set's rmse: 0.00468842

	-0.0047	 = Validation score   (-root_mean_squared_error)
	131.91s	 = Training   runtime
	2.43s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.0 GB
	Ensemble Weights: {'LightGBMLarge': 0.667, 'XGBoost': 0.267, 'ExtraTreesMSE': 0.067}
	-0.0046	 = Validation score   (-root_mean_squared_error)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2092.59s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 896.1 rows/s (2668 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/drive/MyDrive/ML-For-CV-Robustness/datasets/AutogluonModels/ag-20260822_145624")

In [22]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-0.004645,root_mean_squared_error,2.977369,345.498397,0.000458,0.019172,2,True,9
1,LightGBMLarge,-0.004688,root_mean_squared_error,2.434174,131.911205,2.434174,131.911205,1,True,8
2,XGBoost,-0.004898,root_mean_squared_error,0.267084,103.936441,0.267084,103.936441,1,True,6
3,LightGBM,-0.004991,root_mean_squared_error,1.955552,111.614114,1.955552,111.614114,1,True,2
4,LightGBMXT,-0.005495,root_mean_squared_error,2.886207,160.080127,2.886207,160.080127,1,True,1
5,NeuralNetTorch,-0.005710,root_mean_squared_error,0.024336,690.272964,0.024336,690.272964,1,True,7
6,ExtraTreesMSE,-0.005991,root_mean_squared_error,0.275653,109.631578,0.275653,109.631578,1,True,4
7,RandomForestMSE,-0.006560,root_mean_squared_error,0.312938,561.028113,0.312938,561.028113,1,True,3
8,NeuralNetFastAI,-0.006933,root_mean_squared_error,0.037596,191.167501,0.037596,191.167501,1,True,5

In [23]:
predictor.leaderboard(test_df, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-0.004615,-0.004645,root_mean_squared_error,76.206679,2.977369,345.498397,0.030692,0.000458,0.019172,2,True,9
1,LightGBMLarge,-0.004646,-0.004688,root_mean_squared_error,64.027623,2.434174,131.911205,64.027623,2.434174,131.911205,1,True,8
2,LightGBM,-0.004864,-0.004991,root_mean_squared_error,48.230255,1.955552,111.614114,48.230255,1.955552,111.614114,1,True,2
3,XGBoost,-0.004922,-0.004898,root_mean_squared_error,6.711711,0.267084,103.936441,6.711711,0.267084,103.936441,1,True,6
4,LightGBMXT,-0.005369,-0.005495,root_mean_squared_error,70.662203,2.886207,160.080127,70.662203,2.886207,160.080127,1,True,1
5,NeuralNetTorch,-0.005769,-0.005710,root_mean_squared_error,0.354123,0.024336,690.272964,0.354123,0.024336,690.272964,1,True,7
6,ExtraTreesMSE,-0.005967,-0.005991,root_mean_squared_error,5.436652,0.275653,109.631578,5.436652,0.275653,109.631578,1,True,4
7,RandomForestMSE,-0.006677,-0.006560,root_mean_squared_error,3.876890,0.312938,561.028113,3.876890,0.312938,561.028113,1,True,3
8,NeuralNetFastAI,-0.006944,-0.006933,root_mean_squared_error,0.773612,0.037596,191.167501,0.773612,0.037596,191.167501,1,True,5